trip_site_management_homepage:
    path:     /
    defaults: { _controller: TripBookingEngineBundle:Booking:index }
trip_site_management_homepage_hotels:
    path:     /hotels
    defaults: { _controller: TripBookingEngineBundle:Booking:hotels }
trip_site_management_homepage_deals:
    path:     /deals
    defaults: { _controller: TripBookingEngineBundle:Booking:deals }
trip_booking_engine_search:
    path:     /search
    defaults: { _controller: TripBookingEngineBundle:Booking:search }
trip_booking_engine_search_hotel:
    path:     /searchHotel
    defaults: { _controller: TripBookingEngineBundle:Booking:searchHotel }
trip_booking_engine_book:
    path:     /book
    defaults: { _controller: TripBookingEngineBundle:Booking:book }
trip_booking_engine_book_submit:
    path:     /book/submit
    defaults: { _controller: TripBookingEngineBundle:Booking:bookSubmit }
trip_booking_engine_payment:
    path:     /book/payment
    defaults: { _controller: TripBookingEngineBundle:Booking:payment }
trip_booking_engine_success:
    path:     /success
    defaults: { _controller: TripBookingEngineBundle:Booking:success }
trip_booking_engine_confirm:
    path:     /confirm
    defaults: { _controller: TripBookingEngineBundle:Booking:confirm }
trip_booking_engine_payment_payu:
    path:     /payu
    defaults: { _controller: TripBookingEngineBundle:Booking:payu }

trip_booking_engine_apply_coupon:
    path:     /applyCoupon
    defaults: { _controller: TripBookingEngineBundle:Booking:applyCoupon }
trip_booking_engine_customPackage:
    path:     /custom-package
    defaults: { _controller: TripBookingEngineBundle:Booking:customPackage }
trip_booking_engine_testcustomPackage:
    path:     /test-billing-dateails
    defaults: { _controller: TripBookingEngineBundle:Booking:testCustomPackage }

trip_booking_engine_review_custom_package:
    path:     /review/{id}/custom-package
    defaults: { _controller: TripBookingEngineBundle:Booking:reviewCustomPackage }
trip_booking_engine_edit_customer_details:
    path:     /edit/{id}/customer-details
    defaults: { _controller: TripBookingEngineBundle:Booking:editCustomerDetails }
trip_booking_engine_edit_custom_package:
    path:     /edit/{id}/custom-package
    defaults: { _controller: TripBookingEngineBundle:Booking:editCustomPackage }
trip_booking_engine_confirm_custom_package:
    path:     /confirm/{id}/custom-package
    defaults: { _controller: TripBookingEngineBundle:Booking:confirmCustomPackage }
trip_booking_engine_hotel_booking:
    path:     /hotel-booking
    defaults: { _controller: TripBookingEngineBundle:Booking:hotelBooking }

trip_booking_engine_vendor_registraion_form:
    path:     /vendor-registraion-form
    defaults: { _controller: TripBookingEngineBundle:Booking:vendorRegistraion }
trip_booking_engine_vendor_login:
    path:     /test-vendor-login
    defaults: { _controller: TripBookingEngineBundle:Booking:vendorLogin }
trip_booking_engine_test_vendor_login:
    path:     /partner-with-us
    defaults: { _controller: TripBookingEngineBundle:Booking:vendorTestLogin }
trip_booking_engine_test_vendor_password:
    path:     /test-vendor-password
    defaults: { _controller: TripBookingEngineBundle:Booking:vendorTestPassword }
trip_booking_engine_test_vendor_success:
    path:     /test-vendor-success
    defaults: { _controller: TripBookingEngineBundle:Booking:vendorTestSuccess }
trip_booking_engine_vendor_confirm_login:
    path:     /vendor-confirm-login
    defaults: { _controller: TripBookingEngineBundle:Booking:vendorConfirmLogin }
trip_booking_engine_vendor_validate_login:
    path:     /vendor-validate-login
    defaults: { _controller: TripBookingEngineBundle:Booking:vendorValidateLogin }
trip_booking_engine_vendor_reset_password:
    path:     /vendor-reset-password
    defaults: { _controller: TripBookingEngineBundle:Booking:vendorResetPassword }
trip_booking_engine_vendor_reset_pwd_validation:
    path:     /vendor-reset-pwdvalidation
    defaults: { _controller: TripBookingEngineBundle:Booking:vendorResetPasswordValidation }
trip_booking_engine_vendor_profile:
    path:     /vendor-profile
    defaults: { _controller: TripBookingEngineBundle:Booking:vendorProfile }
trip_booking_engine_vendor_edit_login:
    path:     /vendor-edit-login
    defaults: { _controller: TripBookingEngineBundle:Booking:vendorEditLogin }
trip_booking_engine_vendor_edit_validate_login:
    path:     /vendor-edit-validate-login
    defaults: { _controller: TripBookingEngineBundle:Booking:vendorEditValidateLogin }
trip_booking_engine_vendor_add_vehicle:
    path:     /vendor-add-vehicle
    defaults: { _controller: TripBookingEngineBundle:Booking:vendorAddVehicle }
trip_booking_engine_vendor_add_driver:
    path:     /vendor-add-driver
    defaults: { _controller: TripBookingEngineBundle:Booking:vendorAddDriver }  
trip_booking_engine_vendor_list_vehicles:
    path:     /vendor-list-vehicles
    defaults: { _controller: TripBookingEngineBundle:Booking:vendorListVehicles }
trip_booking_engine_vendor_list_drivers:
    path:     /vendor-list-drivers
    defaults: { _controller: TripBookingEngineBundle:Booking:vendorListDrivers }
trip_booking_engine_vendor_edit_driver:
    path:     /vendor-edit-driver
    defaults: { _controller: TripBookingEngineBundle:Booking:vendorEditDriver }  
trip_booking_engine_vendor_remove_driver:
    path:     /vendor-remove-driver
    defaults: { _controller: TripBookingEngineBundle:Booking:vendorRemoveDriver }   
trip_booking_engine_vendor_remove_vehicle:
    path:     /vendor-remove-vehicle
    defaults: { _controller: TripBookingEngineBundle:Booking:vendorRemoveVehicle }  
trip_booking_engine_vendor_edit_vendor:
    path:     /vendor-edit-profile
    defaults: { _controller: TripBookingEngineBundle:Booking:vendorEditProfile} 
trip_booking_engine_booking_bike:
    path:     /booking-bike
    defaults: { _controller: TripBookingEngineBundle:Booking:bookingBike }
trip_booking_engine_confirm_bike:
    path:     /confirm-bike
    defaults: { _controller: TripBookingEngineBundle:Booking:confirmBike }
trip_booking_engine_book_bike_submit:
    path:     /book/bike/submit
    defaults: { _controller: TripBookingEngineBundle:Booking:bookbikeSubmit }
trip_booking_engine_payment_bike:
    path:     /book/payment-bike
    defaults: { _controller: TripBookingEngineBundle:Booking:paymentBike }
remove_trailing_slash:
    path: /{url}
    defaults: { _controller: TripBookingEngineBundle:Booking:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]
trip_booking_engine_vendor_payment:
    path:     /vendor-payment
    defaults: { _controller: TripBookingEngineBundle:Booking:vendorPayment} 
trip_booking_engine_vendor_payment_success:
    path:     /vendor-payment-success
    defaults: { _controller: TripBookingEngineBundle:Booking:vendorPaymentSuccess} 
trip_booking_engine_vendor_payment_fail:
    path:     /vendor-payment-fail
    defaults: { _controller: TripBookingEngineBundle:Booking:vendorPaymentFail} 
trip_booking_engine_vendor_list:
    path:     /vendor-list
    defaults: { _controller: TripBookingEngineBundle:Booking:vendorList} 
trip_booking_engine_vendor_list_view_more:
    path:     /vendor-list-view -more
    defaults: { _controller: TripBookingEngineBundle:Booking:vendorListViewMore} 
trip_booking_engine_dest_tpt:
    path:     /tirupati/{url}
    defaults: { _controller: TripBookingEngineBundle:Booking:destSearch }
trip_booking_engine_dest_ch:
    path:     /chennai/{url}
    defaults: { _controller: TripBookingEngineBundle:Booking:destSearch }
trip_booking_engine_dest_bl:
    path:     /bangalore/{url}
    defaults: { _controller: TripBookingEngineBundle:Booking:destSearch }
trip_booking_engine_dest_kn:
    path:     /bangalore/{url}
    defaults: { _controller: TripBookingEngineBundle:Booking:destSearch }
       