trip_site_management_homepage:
    path:     /
    defaults: { _controller: TripBookingEngineBundle:Booking:index }
trip_site_management_homepage_hotels:
    path:     /hotels
    defaults: { _controller: TripBookingEngineBundle:Booking:hotels }
trip_site_management_homepage_deals:
    path:     /deals
    defaults: { _controller: TripBookingEngineBundle:Booking:deals }
trip_booking_engine_search:
    path:     /search
    defaults: { _controller: TripBookingEngineBundle:Booking:search }
trip_booking_engine_search_hotel:
    path:     /searchHotel
    defaults: { _controller: TripBookingEngineBundle:Booking:searchHotel }
trip_booking_engine_book:
    path:     /book
    defaults: { _controller: TripBookingEngineBundle:Booking:book }
trip_booking_engine_book_submit:
    path:     /book/submit
    defaults: { _controller: TripBookingEngineBundle:Booking:bookSubmit }
trip_booking_engine_payment:
    path:     /book/payment
    defaults: { _controller: TripBookingEngineBundle:Booking:payment }
trip_booking_engine_success:
    path:     /success
    defaults: { _controller: TripBookingEngineBundle:Booking:success }
trip_booking_engine_confirm:
    path:     /confirm
    defaults: { _controller: TripBookingEngineBundle:Booking:confirm }
trip_booking_engine_apply_coupon:
    path:     /applyCoupon
    defaults: { _controller: TripBookingEngineBundle:Booking:applyCoupon }
trip_booking_engine_customPackage:
    path:     /custom-package
    defaults: { _controller: TripBookingEngineBundle:Booking:customPackage }
trip_booking_engine_review_custom_package:
    path:     /review/{id}/custom-package
    defaults: { _controller: TripBookingEngineBundle:Booking:reviewCustomPackage }
trip_booking_engine_edit_customer_details:
    path:     /edit/{id}/customer-details
    defaults: { _controller: TripBookingEngineBundle:Booking:editCustomerDetails }
trip_booking_engine_edit_custom_package:
    path:     /edit/{id}/custom-package
    defaults: { _controller: TripBookingEngineBundle:Booking:editCustomPackage }
trip_booking_engine_confirm_custom_package:
    path:     /confirm/{id}/custom-package
    defaults: { _controller: TripBookingEngineBundle:Booking:confirmCustomPackage }
