trip_site_management_homepage:
    path:     /
    defaults: { _controller: TripBookingEngineBundle:Booking:index }
trip_site_management_homepage_deals:
    path:     /deals
    defaults: { _controller: TripBookingEngineBundle:Booking:deals }
trip_booking_engine_book:
    path:     /book
    defaults: { _controller: TripBookingEngineBundle:Booking:book }
trip_booking_engine_book_submit:
    path:     /book/submit
    defaults: { _controller: TripBookingEngineBundle:Booking:bookSubmit }
trip_booking_engine_payment:
    path:     /book/payment
    defaults: { _controller: TripBookingEngineBundle:Booking:payment }
trip_booking_engine_success:
    path:     /success
    defaults: { _controller: TripBookingEngineBundle:Booking:success }
trip_booking_engine_confirm:
    path:     /confirm
    defaults: { _controller: TripBookingEngineBundle:Booking:confirm }
trip_booking_engine_payment_payu:
    path:     /payu
    defaults: { _controller: TripBookingEngineBundle:Booking:payu }

trip_booking_engine_apply_coupon:
    path:     /applyCoupon
    defaults: { _controller: TripBookingEngineBundle:Booking:applyCoupon }
trip_booking_engine_edit_customer_details:
    path:     /edit/{id}/customer-details
    defaults: { _controller: TripBookingEngineBundle:Booking:editCustomerDetails }
trip_booking_engine_booking_bike:
    path:     /booking-bike
    defaults: { _controller: TripBookingEngineBundle:Booking:bookingBike }
trip_booking_engine_myorder:
    path:     /myorders
    defaults: { _controller: TripBookingEngineBundle:Booking:myorder }
trip_booking_engine_profile:
    path:     /profile
    defaults: { _controller: TripBookingEngineBundle:Booking:profile }
trip_booking_engine_deletedocupload:
    path:     /deletedocupload/{id}
    defaults: { _controller: TripBookingEngineBundle:Booking:deletedocupload }
trip_booking_engine_confirm_bike:
    path:     /confirm-bike
    defaults: { _controller: TripBookingEngineBundle:Booking:confirmBike }
trip_booking_engine_book_bike_submit:
    path:     /bikebook-submit
    defaults: { _controller: TripBookingEngineBundle:Booking:bookbikeSubmit }
trip_booking_engine_bikepayment:
    path:     /bikebooking/submit
    defaults: { _controller: TripBookingEngineBundle:Booking:bikePay }
trip_booking_engine_payment_bike:
    path:     /book/payment-bike
    defaults: { _controller: TripBookingEngineBundle:Booking:paymentBike }
remove_trailing_slash:
    path: /{url}
    defaults: { _controller: TripBookingEngineBundle:Booking:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]

