services:
#    trip_booking_engine.example:
#        class: Trip\BookingEngineBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
     booking.services:
        class: Trip\BookingEngineBundle\DependencyInjection\BookingServices
        arguments: ["@doctrine.orm.entity_manager",'@service_container', @session]