trip_rest_homepage:
    path:     /hello/{name}
    defaults: { _controller: TripRestBundle:Default:index }

trip_rest_getlocation:
    path:     /api/get-location
    defaults: { _controller: TripRestBundle:Rest:index }

trip_rest_getsearch:
    path:     /api/get-search
    defaults: { _controller: TripRestBundle:Rest:search }

trip_rest_getbooking:
    path:     /api/get-bookingsubmit
    defaults: { _controller: TripRestBundle:Rest:bookSubmit }

trip_rest_instamojo_getbooking:
    path:     /api/get-bookinginstamojosubmit
    defaults: { _controller: TripRestBundle:Rest:bookSubmitInstamojo }
    
trip_rest_instamojo_payment:
    path:     /api/get-instamojo
    defaults: { _controller: TripRestBundle:Rest:instamojo }
trip_rest_payu_payment_trips:
    path:     /api/pay/{bookingId}/online/
    defaults: { _controller: TripRestBundle:Rest:payonline }

trip_rest_booking_engine_success:
    path:     /api/customerpaymentconfirmation
    defaults: { _controller: TripRestBundle:Rest:paymentsucess }
    
trip_rest_getpaymentupdate:
    path:     /api/get-paymentupdate
    defaults: { _controller: TripRestBundle:Rest:paymentcomplete }
    
trip_rest_management_homepage_packages:
    path:     /api/get-packages
    defaults: { _controller: TripRestBundle:Restpackages:multipackages }
    
trip_rest_management_homepage_packagedetail_new:
    path:     /api/get-packagedetail
    defaults: { _controller: TripRestBundle:Restpackages:specialPackages }

trip_rest_management_packagebookingsubmit:
    path:     /api/get-packagebookingsubmit
    defaults: { _controller: TripRestBundle:Restpackages:packagebookingsubmit }

trip_rest_management_Loginuserdetails:
    path:     /api/get-logindetail
    defaults: { _controller: TripRestBundle:Rest:userLogin }
trip_rest_management_registeruser:
    path:     /api/user-register
    defaults: { _controller: TripRestBundle:Rest:register }
trip_rest_management_edit_profile:
    path:     /api/edit-profile
    defaults: { _controller: TripRestBundle:Rest:editProfile } 
trip_rest_management_user_bookings:
    path:     /api/user-bookings
    defaults: { _controller: TripRestBundle:Rest:userBookings }
trip_rest_management_user_documents:
    path:     /api/user-documents
    defaults: { _controller: TripRestBundle:Rest:userDocuments }
trip_rest_management_upload_documents:
    path:     /api/upload-documents
    defaults: { _controller: TripRestBundle:Rest:uploadDocuments }
trip_rest_management_uploaded_documents:
    path:     /api/uploaded-documents
    defaults: { _controller: TripRestBundle:Rest:uploadedDocuments } 	
trip_rest_management_homepage_rentbikes:
    path:     /api/get-bikes
    defaults: { _controller: TripRestBundle:Restbikes:bikesonRent}
trip_rest_management_homepage_rentbikes_price_change:
    path:     /api/bike-price-on-change
    defaults: { _controller: TripRestBundle:Restbikes:priceOnChange}
trip_rest_management_homepage_rentbikesbookingdetails:
    path:     /api/get-bikebookingsubmit
    defaults: { _controller: TripRestBundle:Restbikes:bikebookingsubmit}
trip_rest_management_support:
    path:     /api/support
    defaults: { _controller: TripRestBundle:Rest:support } 
