trip_site_management_add_locations:
    path:     /add/locations
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:addLocations }
trip_site_management_booking_search:
    path:     /booking-search
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:bookingSearch }
trip_site_management_bookings:
    path:     /bookings
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:bookings }
trip_site_management_export_bookings:
    path:     /exportBookings
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:exportBookings }
trip_site_management_export_billings:
    path:     /exportBillings
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:exportBillings }
trip_site_management_my_bookings:
    path:     /my-bookings
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:myBookings }
trip_site_management_cancel:
    path:     /cancel-booking
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:cancel }
trip_site_management_change_status:
    path:     /change-status
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:changeStatus }
trip_site_management_verify_booking:
    path:     /verify-bookings
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:cancelVerify }
trip_site_management_cancel_sucess:
    path:     /cancel-sucess
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:cancelConfirm }
trip_site_management_users:
    path:     /users
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:userList }
trip_site_management_contactList:
    path:     /contact-list
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:contactList }
trip_site_management_contact:
    path:     /contact
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:contact }
trip_site_management_about:
    path:     /aboutUs
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:aboutUs }
trip_site_management_terms:
    path:     /privacy-policy
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:terms }
trip_site_management_faq:
    path:     /faq
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:faq }
trip_site_management_bikes_on_rent:
    path:     / 
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:bikesonRent }
trip_site_management_view_bikes:
    path:     /bikes/{url}
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:viewBikes }
trip_site_management_view_bikestpt:
    path:     /tirupati/{url}
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:viewBikes }
trip_site_management_view_bikesblr:
    path:     /bangalore/{url}
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:viewBikes }
trip_site_management_review_viewbikes:
    path:     /search-bikes
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:reviewViewbikes }
trip_site_management_price_viewbikes:
    path:     /search-view-bikes
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:priceViewbikes }
trip_site_management_homepage_bikes_submit:
    path:     /bike/submit
    defaults: { _controller:TripSiteManagementBundle:SiteManagement:bikesSubmit }
trip_site_management_bikes_terms:
    path:     /privacy-policy-bikes
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:bikesterms }
trip_site_management_edit_bikes:
    path:     /edit/{id}/bikes
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:editBikes }
trip_site_management_bikes_list:
    path:     /bikes-list
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:bikesList }
trip_site_management_add_bike:
    path:     /add-bike
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:addBike }  
      
trip_site_management_bike_packages:
    path:     /bikepackages
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:bikepackages }

trip_site_management_bike_package_result:
    path:     /bikepackageresult
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:bikepackageresult }
trip_site_management_bike_packages_tpt:
    path:     /tirupathi/bike-packages-in-tirupati
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:bikepackagesBasedonlocation }
trip_site_management_bike_packages_blr:
    path:     /bengaluru/bike-packages-in-bangalore
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:bikepackagesBasedonlocation }
    
trip_site_management_bikes_packageurl:
    path:     /{cityid}/packages/{packageurl}
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:bikepackagesBasedonlocation }
trip_site_management_bikes_on_rent_tpt:
    path:     /tirupathi/bikes-on-rent-in-tirupati
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:bikesonRentBasedonlocation }
trip_site_management_bikes_on_rent_blr:
    path:     /bengaluru/bikes-on-rent-in-bengaluru
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:bikesonRentBasedonlocation }
    
trip_site_management_bikes_city:
    path:     /{cityid}/bikes/{url}
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:bikesonRentBasedonlocation }

trip_site_management_edit_bikes_maincity:
    path:     /edit/{id}/bikes-maincity
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:editBikesmaincity }
trip_site_management_add_bikecity:
    path:     /add-bikecity
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:addbikescity }
trip_site_management_add_bikecityarea:
    path:     /add-bikecityarea
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:addbikescityarea }
trip_site_management_edit_bikes_city:
    path:     /edit/{id}/bikes-city
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:editBikescity }
trip_site_management_edit_bikes_cityarea:
    path:     /edit/{id}/bikes-cityarea
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:editBikescityarea }
trip_site_management_edit_bikes_package:
    path:     /edit/{id}/bikespackage
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:editBikesPackage }
trip_site_management_delete_bike_package:
    path:     /delete/{id}/bikespackage
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:deleteBikesPackage }
trip_site_management_add_bike_package:
    path:     /add-bikespackage
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:addBikesPackage }        
