
trip_site_management_add_vehicle:
    path:     /add/vehicle
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:addVehicle }
trip_site_management_add_services:
    path:     /add/services
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:addServices }
trip_site_management_add_locations:
    path:     /add/locations
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:addLocations }
trip_site_management_add_hotel:
    path:     /add/hotel
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:addHotel }
trip_site_management_homepage_packages:
    path:     /packages
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:packages }
trip_site_management_homepage_package_submit:
    path:     /package/submit
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:packageSubmit }
trip_site_management_booking_search:
    path:     /booking-search
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:bookingSearch }
trip_site_management_bookings:
    path:     /bookings
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:bookings }
trip_site_management_my_bookings:
    path:     /my-bookings
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:myBookings }
trip_site_management_cancel:
    path:     /cancel-booking
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:cancel }
trip_site_management_change_status:
    path:     /change-status
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:changeStatus }
trip_site_management_verify_booking:
    path:     /verify-bookings
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:cancelVerify }
trip_site_management_cancel_sucess:
    path:     /cancel-sucess
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:cancelConfirm }
trip_site_management_users:
    path:     /users
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:userList }
trip_site_management_contactList:
    path:     /contact-list
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:contactList }
trip_site_management_contact:
    path:     /contact
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:contact }
trip_site_management_about:
    path:     /aboutUs
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:aboutUs }
trip_site_management_terms:
    path:     /privacy-policy
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:terms }
trip_site_management_faq:
    path:     /faq
    defaults: { _controller: TripSiteManagementBundle:SiteManagement:faq }
